services:
  postgres:
    image: postgres:16
    container_name: drs-postgres
    restart: always
    environment:
      POSTGRES_USER: drs_user
      POSTGRES_PASSWORD: drs_password
      POSTGRES_DB: drs_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 
