# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc import collector_pb2 as collector__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in collector_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CollectorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CollectMetrics = channel.unary_unary(
                '/drs.collector.CollectorService/CollectMetrics',
                request_serializer=collector__pb2.CollectMetricsRequest.SerializeToString,
                response_deserializer=collector__pb2.CollectMetricsResponse.FromString,
                _registered_method=True)
        self.CollectEvents = channel.unary_unary(
                '/drs.collector.CollectorService/CollectEvents',
                request_serializer=collector__pb2.CollectEventsRequest.SerializeToString,
                response_deserializer=collector__pb2.CollectEventsResponse.FromString,
                _registered_method=True)


class CollectorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CollectMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CollectEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CollectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CollectMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectMetrics,
                    request_deserializer=collector__pb2.CollectMetricsRequest.FromString,
                    response_serializer=collector__pb2.CollectMetricsResponse.SerializeToString,
            ),
            'CollectEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectEvents,
                    request_deserializer=collector__pb2.CollectEventsRequest.FromString,
                    response_serializer=collector__pb2.CollectEventsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'drs.collector.CollectorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('drs.collector.CollectorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CollectorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CollectMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drs.collector.CollectorService/CollectMetrics',
            collector__pb2.CollectMetricsRequest.SerializeToString,
            collector__pb2.CollectMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CollectEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drs.collector.CollectorService/CollectEvents',
            collector__pb2.CollectEventsRequest.SerializeToString,
            collector__pb2.CollectEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
