# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: collector.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'collector.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63ollector.proto\x12\rdrs.collector\"\x17\n\x15\x43ollectMetricsRequest\"9\n\x16\x43ollectMetricsResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x16\n\x14\x43ollectEventsRequest\"`\n\x15\x43ollectEventsResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\nhas_events\x18\x02 \x01(\x08\x12\x13\n\x0b\x65vent_count\x18\x03 \x01(\x05\x12\x0e\n\x06\x65vents\x18\x04 \x03(\t2\xd1\x01\n\x10\x43ollectorService\x12_\n\x0e\x43ollectMetrics\x12$.drs.collector.CollectMetricsRequest\x1a%.drs.collector.CollectMetricsResponse\"\x00\x12\\\n\rCollectEvents\x12#.drs.collector.CollectEventsRequest\x1a$.drs.collector.CollectEventsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'collector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COLLECTMETRICSREQUEST']._serialized_start=34
  _globals['_COLLECTMETRICSREQUEST']._serialized_end=57
  _globals['_COLLECTMETRICSRESPONSE']._serialized_start=59
  _globals['_COLLECTMETRICSRESPONSE']._serialized_end=116
  _globals['_COLLECTEVENTSREQUEST']._serialized_start=118
  _globals['_COLLECTEVENTSREQUEST']._serialized_end=140
  _globals['_COLLECTEVENTSRESPONSE']._serialized_start=142
  _globals['_COLLECTEVENTSRESPONSE']._serialized_end=238
  _globals['_COLLECTORSERVICE']._serialized_start=241
  _globals['_COLLECTORSERVICE']._serialized_end=450
# @@protoc_insertion_point(module_scope)
