# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc import engine_pb2 as engine__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EngineServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComputeDecision = channel.unary_unary(
                '/drs.engine.EngineService/ComputeDecision',
                request_serializer=engine__pb2.ComputeDecisionRequest.SerializeToString,
                response_deserializer=engine__pb2.ComputeDecisionResponse.FromString,
                _registered_method=True)
        self.ExecuteMigration = channel.unary_unary(
                '/drs.engine.EngineService/ExecuteMigration',
                request_serializer=engine__pb2.ExecuteMigrationRequest.SerializeToString,
                response_deserializer=engine__pb2.ExecuteMigrationResponse.FromString,
                _registered_method=True)
        self.GetLatestDecision = channel.unary_unary(
                '/drs.engine.EngineService/GetLatestDecision',
                request_serializer=engine__pb2.GetLatestDecisionRequest.SerializeToString,
                response_deserializer=engine__pb2.GetLatestDecisionResponse.FromString,
                _registered_method=True)
        self.GetPendingPlan = channel.unary_unary(
                '/drs.engine.EngineService/GetPendingPlan',
                request_serializer=engine__pb2.GetPendingPlanRequest.SerializeToString,
                response_deserializer=engine__pb2.GetPendingPlanResponse.FromString,
                _registered_method=True)
        self.RejectPendingPlan = channel.unary_unary(
                '/drs.engine.EngineService/RejectPendingPlan',
                request_serializer=engine__pb2.RejectPendingPlanRequest.SerializeToString,
                response_deserializer=engine__pb2.RejectPendingPlanResponse.FromString,
                _registered_method=True)
        self.ApprovePendingPlan = channel.unary_unary(
                '/drs.engine.EngineService/ApprovePendingPlan',
                request_serializer=engine__pb2.ApprovePendingPlanRequest.SerializeToString,
                response_deserializer=engine__pb2.ApprovePendingPlanResponse.FromString,
                _registered_method=True)


class EngineServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ComputeDecision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteMigration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatestDecision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPendingPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RejectPendingPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApprovePendingPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComputeDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeDecision,
                    request_deserializer=engine__pb2.ComputeDecisionRequest.FromString,
                    response_serializer=engine__pb2.ComputeDecisionResponse.SerializeToString,
            ),
            'ExecuteMigration': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteMigration,
                    request_deserializer=engine__pb2.ExecuteMigrationRequest.FromString,
                    response_serializer=engine__pb2.ExecuteMigrationResponse.SerializeToString,
            ),
            'GetLatestDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestDecision,
                    request_deserializer=engine__pb2.GetLatestDecisionRequest.FromString,
                    response_serializer=engine__pb2.GetLatestDecisionResponse.SerializeToString,
            ),
            'GetPendingPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPendingPlan,
                    request_deserializer=engine__pb2.GetPendingPlanRequest.FromString,
                    response_serializer=engine__pb2.GetPendingPlanResponse.SerializeToString,
            ),
            'RejectPendingPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.RejectPendingPlan,
                    request_deserializer=engine__pb2.RejectPendingPlanRequest.FromString,
                    response_serializer=engine__pb2.RejectPendingPlanResponse.SerializeToString,
            ),
            'ApprovePendingPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.ApprovePendingPlan,
                    request_deserializer=engine__pb2.ApprovePendingPlanRequest.FromString,
                    response_serializer=engine__pb2.ApprovePendingPlanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'drs.engine.EngineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('drs.engine.EngineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EngineService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ComputeDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drs.engine.EngineService/ComputeDecision',
            engine__pb2.ComputeDecisionRequest.SerializeToString,
            engine__pb2.ComputeDecisionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteMigration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drs.engine.EngineService/ExecuteMigration',
            engine__pb2.ExecuteMigrationRequest.SerializeToString,
            engine__pb2.ExecuteMigrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLatestDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drs.engine.EngineService/GetLatestDecision',
            engine__pb2.GetLatestDecisionRequest.SerializeToString,
            engine__pb2.GetLatestDecisionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPendingPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drs.engine.EngineService/GetPendingPlan',
            engine__pb2.GetPendingPlanRequest.SerializeToString,
            engine__pb2.GetPendingPlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RejectPendingPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drs.engine.EngineService/RejectPendingPlan',
            engine__pb2.RejectPendingPlanRequest.SerializeToString,
            engine__pb2.RejectPendingPlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApprovePendingPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drs.engine.EngineService/ApprovePendingPlan',
            engine__pb2.ApprovePendingPlanRequest.SerializeToString,
            engine__pb2.ApprovePendingPlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
