# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc import scoring_pb2 as scoring__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in scoring_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScoringServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScoreCluster = channel.unary_unary(
                '/drs.scoring.ScoringService/ScoreCluster',
                request_serializer=scoring__pb2.ScoreClusterRequest.SerializeToString,
                response_deserializer=scoring__pb2.ScoreClusterResponse.FromString,
                _registered_method=True)
        self.ScoreHost = channel.unary_unary(
                '/drs.scoring.ScoringService/ScoreHost',
                request_serializer=scoring__pb2.ScoreHostRequest.SerializeToString,
                response_deserializer=scoring__pb2.ScoreHostResponse.FromString,
                _registered_method=True)


class ScoringServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ScoreCluster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScoreHost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScoringServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ScoreCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.ScoreCluster,
                    request_deserializer=scoring__pb2.ScoreClusterRequest.FromString,
                    response_serializer=scoring__pb2.ScoreClusterResponse.SerializeToString,
            ),
            'ScoreHost': grpc.unary_unary_rpc_method_handler(
                    servicer.ScoreHost,
                    request_deserializer=scoring__pb2.ScoreHostRequest.FromString,
                    response_serializer=scoring__pb2.ScoreHostResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'drs.scoring.ScoringService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('drs.scoring.ScoringService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScoringService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ScoreCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drs.scoring.ScoringService/ScoreCluster',
            scoring__pb2.ScoreClusterRequest.SerializeToString,
            scoring__pb2.ScoreClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScoreHost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drs.scoring.ScoringService/ScoreHost',
            scoring__pb2.ScoreHostRequest.SerializeToString,
            scoring__pb2.ScoreHostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
