# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scoring.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'scoring.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rscoring.proto\x12\x0b\x64rs.scoring\"\x15\n\x13ScoreClusterRequest\"%\n\x14ScoreClusterResponse\x12\r\n\x05score\x18\x01 \x01(\x01\"#\n\x10ScoreHostRequest\x12\x0f\n\x07host_id\x18\x01 \x01(\t\"\"\n\x11ScoreHostResponse\x12\r\n\x05score\x18\x01 \x01(\x01\x32\xb5\x01\n\x0eScoringService\x12U\n\x0cScoreCluster\x12 .drs.scoring.ScoreClusterRequest\x1a!.drs.scoring.ScoreClusterResponse\"\x00\x12L\n\tScoreHost\x12\x1d.drs.scoring.ScoreHostRequest\x1a\x1e.drs.scoring.ScoreHostResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scoring_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCORECLUSTERREQUEST']._serialized_start=30
  _globals['_SCORECLUSTERREQUEST']._serialized_end=51
  _globals['_SCORECLUSTERRESPONSE']._serialized_start=53
  _globals['_SCORECLUSTERRESPONSE']._serialized_end=90
  _globals['_SCOREHOSTREQUEST']._serialized_start=92
  _globals['_SCOREHOSTREQUEST']._serialized_end=127
  _globals['_SCOREHOSTRESPONSE']._serialized_start=129
  _globals['_SCOREHOSTRESPONSE']._serialized_end=163
  _globals['_SCORINGSERVICE']._serialized_start=166
  _globals['_SCORINGSERVICE']._serialized_end=347
# @@protoc_insertion_point(module_scope)
