"""Application-wide constants"""

DEFAULT_METRIC_COUNT = 10
MAX_METRIC_COUNT = 5000
DEFAULT_LOOKBACK_HOURS = 1
MAX_LOOKBACK_HOURS = 30

METRIC_TYPE_MEMORY = "memory"
METRIC_TYPE_CPU = "cpu"
METRIC_TYPE_SWAP = "swap"
METRIC_TYPE_RUNNING_VM = "running_vm"

VALID_METRIC_TYPES = {
    METRIC_TYPE_MEMORY,
    METRIC_TYPE_CPU,
    METRIC_TYPE_SWAP,
    METRIC_TYPE_RUNNING_VM,
}

JOB_COMPUTE_NODE = "compute-node-exporter"
JOB_LIBVIRT = "libvirt-exporter"

DEFAULT_CONSUMER_GROUP = "metrics_group"
DEFAULT_CONSUMER_NAME = "metrics_consumer"
DEFAULT_STREAM_KEY = "metrics:stream"

SCHEDULER_COLLECTION_INTERVAL_MINUTES = 5
SCHEDULER_LOOKBACK = 5
SCHEDULER_QUERY_STEP = "15s"

HTTP_REQUEST_TIMEOUT = 30
REDIS_CONNECTION_TIMEOUT = 10

ENV_DEVELOPMENT = "development"
ENV_PRODUCTION = "production"
