CPU_METRIC = "cpu"
RAM_METRIC = "ram"
SWAP_METRIC = "swap"
RUNNING_VM_METRIC = "running_vm"

METRIC_COLUMNS = [CPU_METRIC, RAM_METRIC, SWAP_METRIC]
HISTORY_COLUMNS = ["timestamp", "host", CPU_METRIC, RAM_METRIC, SWAP_METRIC, RUNNING_VM_METRIC]

EVENT_MIGRATE = "migrate"
EVENT_CREATE = "create"
EVENT_DELETE = "delete"
VM_EVENT_ACTIONS = [EVENT_MIGRATE, EVENT_CREATE, EVENT_DELETE]

STATUS_SKIPPED_BY_EVENT = "skipped_by_event"
STATUS_CURRENT_IMBALANCED = "current_imbalanced"
STATUS_CURRENT_BALANCED = "current_balanced"
STATUS_PREDICTED_IMBALANCED = "predicted_imbalanced"
STATUS_PREDICTED_BALANCED = "predicted_balanced"
STATUS_MIGRATION_PLANNED = "migration_planned"
STATUS_MIGRATION_EXECUTING = "migration_executing"
STATUS_MIGRATION_EXECUTED = "migration_executed"
STATUS_MIGRATION_FAILED = "migration_failed"
STATUS_MIGRATION_REJECTED = "migration_rejected"
STATUS_REEVALUATING = "reevaluating"
STATUS_ERROR = "error"
